CREATE OR REPLACE VIEW TOP_FIRST_NAME AS
SELECT TOP 5
    split_part(trim(VALUE::varchar), ' ', 1) AS FIRST_NAME,
    count(*) AS NAME_COUNT
FROM DIM_SHOW, LATERAL flatten(input => split("CAST", ','))
GROUP BY FIRST_NAME;

CREATE OR REPLACE VIEW TOP_LONGEST_RUN_FROM_RELEASE AS
SELECT TOP 5
    DATE_ADDED,
    to_date(RELEASE_YEAR::varchar, 'YYYY') AS RELEASE_DATE,
    datediff(DAY, RELEASE_DATE, DATE_ADDED) AS DIFF
FROM DIM_SHOW
WHERE DATE_ADDED IS NOT null AND RELEASE_DATE IS NOT null
ORDER BY DIFF DESC
