CREATE OR REPLACE STREAM NETFLIX_STREAM ON TABLE JASON.RAW.NETFLIX
APPEND_ONLY = TRUE;

CREATE OR REPLACE PROCEDURE JASON.RAW.NETFLIX_ELT()
RETURNS VARCHAR
LANGUAGE JAVASCRIPT
EXECUTE AS CALLER
AS
$$

snowflake.execute({sqlText: `
    COPY INTO JASON.RAW.NETFLIX FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');
    `});

snowflake.execute({sqlText: `
    MERGE INTO JASON.RAW.DIM_SHOW T
    USING JASON.RAW.NETFLIX_STREAM S ON
    S."SHOW_ID" = T."SHOW_ID"
    WHEN MATCHED THEN UPDATE SET
    T."TYPE" = S."TYPE",
    T."TITLE" = S."TITLE",
    T."DIRECTOR" = S."DIRECTOR",
    T."CAST" = S."CAST",
    T."COUNTRY" = S."COUNTRY",
    T."DATE_ADDED" = S."DATE_ADDED",
    T."RELEASE_YEAR" = S."RELEASE_YEAR",
    T."RATING" = S."RATING",
    T."DURATION" = S."DURATION",
    T."LISTED_IN" = S."LISTED_IN",
    T."DESCRIPTION" = S."DESCRIPTION"
    WHEN NOT MATCHED THEN INSERT
    ("SHOW_ID", "TYPE", "TITLE", "DIRECTOR", "CAST", "COUNTRY", "DATE_ADDED", "RELEASE_YEAR", "RATING", "DURATION", "LISTED_IN", "DESCRIPTION")
    VALUES
    (S."SHOW_ID", S."TYPE", S."TITLE", S."DIRECTOR", S."CAST", S."COUNTRY", S."DATE_ADDED", S."RELEASE_YEAR", S."RATING", S."DURATION", S."LISTED_IN", S."DESCRIPTION");
    `});
    $$;

CREATE TASK NETFLIX_ELT_TASK
    WAREHOUSE = COMPUTE
    SCHEDULE = '5 MINUTE'
WHEN
    SYSTEM$STREAM_HAS_DATA ('JASON.RAW.NETFLIX_STREAM')
AS
    CALL NETFLIX_ELT();

-- GRANT EXECUTE TASK TO ROLE
--GRANT EXECUTE TASK ON ACCOUNT TO ROLE SYSADMIN;

-- TO RUN MANUALLY
-- EXECUTE TASK NETFLIX_ELT_TASK

-- TO TURN ON
-- ALTER TASK NETFLIX_ELT_TASK RESUME
