CREATE TASK NETFLIX_ELT_TASK
    WAREHOUSE = COMPUTE
    SCHEDULE = '5 MINUTE'
AS
    COPY INTO JASON.RAW.NETFLIX FILE_FORMAT = (TYPE = CSV FIELD_DELIMITER = ',' SKIP_HEADER = 1 FIELD_OPTIONALLY_ENCLOSED_BY = '"');

-- GRANT EXECUTE TASK TO ROLE
--GRANT EXECUTE TASK ON ACCOUNT TO ROLE SYSADMIN;

-- TO RUN
-- EXECUTE TASK NETFLIX_ELT_TASK
